from app.models.department import Department
from app.models.city import City
from app.models.commune import Commune
from app.models.neighborhood import Neighborhood
from app.models.point import Point
from app.models.annotation import Annotation
from app.models.category import Category
from app.models.entity import Entity
from app.models.interested_party import InterestedParty
from app.models.vote import Vote
from app.models.citizen import Citizen
from app.models.annotation_category import AnnotationCategory
from app.models.evidence import Evidence
from app.models.official import Official
